- name: Install Docker, pull image, and run container
  hosts: all
  become: true
  tasks:

    - name: Install prerequisite packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
      when: ansible_os_family == "Debian"

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: ansible_os_family == "Debian"

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Docker
      apt:
        name: docker-ce
        state: latest
      when: ansible_os_family == "Debian"

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: true

    - name: Remove all existing Docker containers
      shell: docker rm -f $(docker ps -aq)
      ignore_errors: true
      when: ansible_os_family == "Debian"

    - name: Remove all existing Docker images
      shell: docker rmi -f $(docker images -aq)
      ignore_errors: true
      when: ansible_os_family == "Debian"
    

    - name: Pull Docker image
      ansible.builtin.shell: docker pull mahmoudamr/jenkins_image02:latest
      args:
        warn: false

    - name: Run Docker container
      ansible.builtin.shell: docker run -p 5000:5000 -d --name docker_container mahmoudamr/jenkins_image02
      args:
        warn: false



