- name: Install Docker, pull image, and run container
  hosts: all
  become: true
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install prerequisite packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
      when: ansible_os_family == "Debian"

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: ansible_os_family == "Debian"

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Docker
      apt:
        name: docker-ce
        state: latest
      when: ansible_os_family == "Debian"

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: true

    - name: Pull Docker image
      ansible.builtin.shell: docker pull nginx:latest
      args:
        warn: false

    - name: Run Docker container
      ansible.builtin.shell: docker run -d --name docker_container mahmoudamr/nanoimg_v2
      args:
        warn: false
